-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'SUPPORT_TICKET_MESSAGE';
ALTER TYPE "NotificationType" ADD VALUE 'SUPPORT_TICKET_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'SUPPORT_TICKET_CLOSED';
